### ISSUE TITLE
参加者オブジェクトに新郎側 or 新婦側かの値がほしい

### ISSUE THREAD

**Issue by gassi4731** [WeddingCamp/wedding-kanshasai-protobuf#72]
## About

参加者オブジェクトに新郎側 or 新婦側かの値がほしい
（新郎/新婦のそれぞれの写真も格納できたら嬉しいな）

**Comment by gassi4731** [comment]
`ListParticipantRequest`で、新郎側 or 新婦側 or 全部 を選択できるようになるとすごくすごくすごく嬉しい。

#75 でissueに変更

**Comment by mizucoffee** [comment]
> 新郎/新婦のそれぞれの写真も格納できたら嬉しいな
これを実装するためだけにテーブル増やすのは中々つらいので、データはホストするから画像の切り分けはフロントでやってもらえると...🙏
