### ISSUE TITLE
`ListParticipantRequest`で、新郎側 or 新婦側 or 全部 を選択できるようになるとすごくすごくすごく嬉しい。

### ISSUE THREAD

**Issue by gassi4731** [WeddingCamp/wedding-kanshasai-protobuf#75]
## About

`ListParticipantRequest`で、新郎側 or 新婦側 or 全部 を選択できるようになるとすごくすごくすごく嬉しい。

#72 と関連

**Comment by mizucoffee** [comment]
optionalとしてParticipantTypeを受け付けるようにしたので、指定したら絞り込み、未指定で全件となるように実装します。
