### ISSUE TITLE
Streamイベント系、disconnectするイベントもあったほうがよさそう

### ISSUE THREAD

**Issue by gassi4731** [WeddingCamp/wedding-kanshasai-protobuf#76]
## About

クライアント側でStreamを停止することはできるが、それをサーバー側に通知することができない。

## Reference

https://zenn.dev/umibows/articles/628be910312b75#%E8%A8%AD%E8%A8%88

**Comment by mizucoffee** [comment]
Closeしたら一応サーバ側で切断処理を行えてるのでCloseでOKそう。
画面閉じてもClose出来てる。
